DATASET_DIR = "/Users/sahandzarrinkoub/Documents/Programming/DD2424DeepLearning/project/repo/SeaLionCounting/TrainSmall2/"
TRAIN_DIR = DATASET_DIR + "Train/"
TRAIN_DOTTED_DIR = DATASET_DIR + "TrainDotted/"
COORDINATES_DIR = DATASET_DIR + "Coordinates/"
BOXES_DIR = DATASET_DIR + "Boxes/"
TEST_DIR = DATASET_DIR + "Test/"
