DATASET_DIR = "//home/riccardo/git/SeaLionCounting/dataset/"
TRAIN_DIR = DATASET_DIR + "Train/"
TRAIN_DOTTED_DIR = DATASET_DIR + "TrainDotted/"
TEST_DIR = DATASET_DIR + "Test/"
TEST_DOTTED_DIR = DATASET_DIR + "TestDotted/"
COORDINATES_DIR = DATASET_DIR + "Coordinates/"
BOXES_DIR = DATASET_DIR + "Boxes/"
